### ISSUE TITLE
Bonus Mode

### ISSUE THREAD

**Issue by UncivilEngineer** [mjocean/PyProcGameHD-SkeletonGame#11]
Could you explain how the bonus mode is supposed to work?

**Comment by mjocean** [comment]
BonusMode remains somewhat incomplete, but I've just committed a basic functionality.  You can see [the changelog here](https://github.com/mjocean/PyProcGameHD-SkeletonGame/commit/4351dbaa2367c66e87f54fe5d362c990d5c937b9)

Basic usage is as such:
*optional*
1. Define a bonus definitions yaml file which associates names with point values: [example bonus_defs.yaml](https://github.com/mjocean/PyProcGameHD-SkeletonGame/blob/dev/SampleGame/config/bonus_defs.yaml)
2. Pull the bonus definitions into your game code in your main game class using the `define_bonuses()` method which takes a file as an argument [example from SampleGame](https://github.com/mjocean/PyProcGameHD-SkeletonGame/blob/dev/SampleGame/T2Game.py#L60).

*Required*:
1. From some mode code, you can call `self.game.bonus(`_name of bonus_`)`
* if you do not have that bonus pre-defined, you will want to pass a named argument: `value` which is the number of points.

I will eventually be adding constraints for the bonuses, which is the number of each bonus allowed per ball and per game.
