### ISSUE TITLE
Four players slows machine

### ISSUE THREAD

**Issue by joshkugler** [mjocean/PyProcGameHD-SkeletonGame#4]
The SG four play display is creating new layers each time through,  which is impacting performance significantly, given the frequency of those hits.  Needs to be changed so layers created just once and set_text used, like it is done for one player.

**Comment by mjocean** [comment]
Fixed in [7/7/2016 commit.](https://github.com/mjocean/PyProcGameHD-SkeletonGame/commit/cfd1da245e5c7b79faea9332095ce858578e0964)
