### ISSUE TITLE
Enhancement: Attract layer with scrolling text.

### ISSUE THREAD

**Issue by scottdanesi** [mjocean/PyProcGameHD-SkeletonGame#6]
Hey Team,
We should look at adding a scrolling layer to the attract mode on SG.  You know, for a "Special Thanks" kind of section.

**Comment by mjocean** [comment]
[`PanningLayer`](https://github.com/mjocean/PyProcGameHD-SkeletonGame/blob/master/procgame/dmd/layers.py#L893) (scrolls any type of layer) exists, as does the [`MarkupLayer`](https://github.com/mjocean/PyProcGameHD-SkeletonGame/blob/master/procgame/dmd/markup.py) (use to generate long layers of text), but not every layer type is exposed through the yaml interface.  It is worth some discussion to figure out which types of layers we want to expose through that YAML interface.  

To do this in code, here is an example:

```
    credits_frame = gen.frame_for_markup("""
#Special thanks to:#
{multimorphic-logo-color}
[Gerry Stellenberg]
[Adam Preble]
[Josh (Rosh)]
[Scott Danesi]
""")
    thanksto = dmd.PanningLayer(width=self.game.dmd.width, height=self.game.dmd.height, frame=credits_frame, origin=(0,-140), translate=(0,4), bounce=False)
    self.layer = thanksto
```

**Comment by scottdanesi** [comment]
Thanks Michael, I think there are some really cool features that we could potentially expose to the YAML interface.  Let me know if you would like to get a discussion going.

**Comment by mjocean** [comment]
Closed.  This and more were added in the most recent commit. [here](https://github.com/mjocean/PyProcGameHD-SkeletonGame/commit/eecf5589db790ed3cb7b8ca3c0b09412c3184288)

Docs:
[http://pinballprogramming.com/display-layer-markup-language/](http://pinballprogramming.com/display-layer-markup-language/)
